apiVersion: v2
name: delivery-service
description: A Helm chart for Agri Platform Delivery Service
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - agri-platform
  - delivery-service
  - microservices
