version: "3.9"

networks:
  agri-net:
    driver: bridge

services:
  # ======================
  # INFRASTRUCTURE
  # ======================

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [agri-net]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on: [zookeeper]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks: [agri-net]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: agri
      POSTGRES_PASSWORD: agri
      POSTGRES_DB: agri
    ports:
      - "5432:5432"
    networks: [agri-net]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: [agri-net]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks: [agri-net]

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    networks: [agri-net]

  tempo:
    image: grafana/tempo:2.3.0
    ports:
      - "3200:3200"
    networks: [agri-net]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    ports:
      - "4317:4317"
      - "4318:4318"
    networks: [agri-net]

  # ======================
  # APPLICATION SERVICES
  # ======================

  order-service:
    image: scamlux3221/order-service:${TAG}
    depends_on: [kafka, postgres]
    ports:
      - "3001:3001"
    networks: [agri-net]

  inventory-service:
    image: scamlux3221/inventory-service:${TAG}
    depends_on: [kafka]
    networks: [agri-net]

  payment-service:
    image: scamlux3221/payment-service:${TAG}
    depends_on: [kafka]
    networks: [agri-net]

  query-service:
    image: scamlux3221/query-service:${TAG}
    depends_on: [kafka]
    networks: [agri-net]
