version: "3.9"

services:
  order-service:
    image: order-service:${TAG}
    ports:
      - "3001:3001"

  inventory-service:
    image: inventory-service:${TAG}

  payment-service:
    image: payment-service:${TAG}

  query-service:
    image: query-service:${TAG}
