services:
  order-service:
    image: scamlux3221/order-service:${TAG}
    ports:
      - "3001:3001"

  inventory-service:
    image: scamlux3221/inventory-service:${TAG}

  payment-service:
    image: scamlux3221/payment-service:${TAG}

  query-service:
    image: scamlux3221/query-service:${TAG}
