apiVersion: v2
name: product-service
description: A Helm chart for Agri Platform Product Service
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - agri-platform
  - product-service
  - microservices
