apiVersion: v2
name: order-service
description: A Helm chart for Agri Platform Order Service
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - agri-platform
  - order-service
  - microservices
